FROM ubuntu:focal
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get -y install default-jre-headless
RUN apt-get install -y wget unzip python3 python3-pip python3-distutils build-essential
RUN apt-get install -y maven
RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
RUN apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io
COPY . /code
#RUN source /root/nvm.sh && nvm install && nvm use
WORKDIR /code
CMD bash