# This action runs unit tests for the OSCAL (schematron) validations to ensure validations
# are working against known samples
name: "OSCAL Validations: Unit Tests"

# Triggered when code is pushed to any branch in a repository
on: push

# the job requires some dependencies to be installed (including submodules), runs the tests, and then reports results
jobs:
  # one job that runs tests
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    # Checkout repository and its submodules
    steps:
      # Check-out the repository under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read node version from `.nvmrc` file
        id: nvmrc
        shell: bash
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Install required node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}

      # Initialize the workspace with submodules and dependencies.
      - name: Initialize workspace
        shell: bash
        run: make init

      # Compile Schematron to XSL.
      - name: Compile Schematron
        shell: bash
        run: make build-validations

      - name: Run complete test suite
        shell: bash
        if: runner.os == 'Linux'
        run: |
          make test

      - name: Run limited test suite
        shell: bash
        if: runner.os == 'Windows'
        run: |
          make test-validations test-web

      # Sets the test report path for visibility
      - name: Publish XSpec Test Results
        uses: mikepenz/action-junit-report@v1
        if: runner.os == 'Linux'
        with:
          report_paths: "**/report/test/*junit.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Publish the test summary as comment on the PR
      - name: Publish XSpec Test Results Summary
        uses: EnricoMi/publish-unit-test-result-action@v1.15
        if: runner.os == 'Linux'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: XSpec Test Results
          files: "**/report/test/*junit.xml"
          report_individual_runs: true
          deduplicate_classes_by_file_name: false

      - name: Upload Resulting Schematron SVRL Report
        uses: actions/upload-artifact@27bce4eee761b5bc643f46a8dfb41b430c8d05f6 # v2
        if: runner.os == 'Linux'
        with:
          name: fedramp-automation-validation-unit-tests-${{ github.sha }}
          path: |
            ./src/validations/report/schematron/**/*.*
            ./src/validations/report/test/**/*.*
          if-no-files-found: error
